server.port=8020
#http://localhost:8020
spring.application.name=config-server

# Git backend
spring.cloud.config.server.git.url=https://github.com/KARRTHIKKKK/AppConfiguration
spring.cloud.config.server.git.username=KARRTHIKKKK
spring.cloud.config.server.git.password=${GIT_PAT_TOKEN}

spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main